import {
  Award,
  BarChart3,
  BookOpen,
  Check,
  Compass,
  CreditCard,
  Database,
  Folder,
  Gauge,
  GitBranch,
  Globe,
  Heart,
  HelpCircle,
  Layers,
  Layout,
  LineChart,
  Link2,
  Mail,
  Megaphone,
  MessageSquare,
  Monitor,
  PenTool,
  Play,
  Rocket,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Map the icon-name strings used in seed data to Lucide components. */
const MAP: Record<string, LucideIcon> = {
  monitor: Monitor,
  megaphone: Megaphone,
  "share-2": Share2,
  share: Share2,
  users: Users,
  "trending-up": TrendingUp,
  trending: TrendingUp,
  sparkles: Sparkles,
  compass: Compass,
  check: Check,
  link: Link2,
  target: Target,
  search: Search,
  "bar-chart-3": BarChart3,
  "line-chart": LineChart,
  settings: Settings,
  shield: Shield,
  rocket: Rocket,
  globe: Globe,
  mail: Mail,
  "pen-tool": PenTool,
  layout: Layout,
  "shopping-bag": ShoppingBag,
  zap: Zap,
  wrench: Wrench,
  gauge: Gauge,
  "book-open": BookOpen,
  "help-circle": HelpCircle,
  "git-branch": GitBranch,
  layers: Layers,
  workflow: Workflow,
  database: Database,
  "credit-card": CreditCard,
  star: Star,
  award: Award,
  heart: Heart,
  "message-square": MessageSquare,
  play: Play,
  folder: Folder,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = MAP[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden="true" />;
}

export function hasIcon(name: string): boolean {
  return name in MAP;
}
